version: '3.8'

services:
  app:
    image: dexterx11/healium:latest
    ports:
      - "80:80"
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GOOGLE_CALLBACK_URI: ${GOOGLE_CALLBACK_URI}
      GOOGLE_APPLICATION_CREDENTIALS: /var/www/html/credentials/gcp-credentials.json
      GCP_STORAGE_BUCKET: ${GCP_STORAGE_BUCKET}
    volumes:
      - ./storage:/var/www/html/storage
      - /opt/secrets/google:/var/www/html/credentials:ro
    deploy:
      mode: replicated
      replicas: 9
      restart_policy:
        condition: on-failure